### ISSUE TITLE
Backup fails when Roam subscription lapses

### ISSUE THREAD

**Issue by ketilmo** [everruler12/roam2github#14]
Hi,

Thanks for creating a stable backup solution for Roam. Here is a specific issue that I have encountered recently: When the Roam subscription lapses, the backup script will start failing on every run. This is probably due to a modal popup with a subscription reminder that appears while opening the Roam database in question. However, it is still possible to export the database, so the problem can likely be worked around. I plan to renew my subscription imminently, but I would be happy to provide the information needed to handle this scenario.

Kind regards,
Ketil

**Comment by everruler12** [comment]
Hi Ketil,

I didn't know about the subscription modal. If you could take a screenshot
of the modal, that would help. And even more, if you can right-click it and
"Inspect element", and send a screenshot of that as well.

Thanks for letting me know,
Erik

**Comment by ketilmo** [comment]
Hi Erik,

Thanks for your fast feedback. I have grabbed a few screenshots of the scenario, and hope it's sufficient for you to be able to work around the state. Let me know if you want me to test anything before I renew my plan.

Thanks again for your help!

Kind regards,
Ketil

![Modal](https://user-images.githubusercontent.com/8332946/117483125-9a498800-af65-11eb-8ffe-68a6a0594cdf.png)

![Code](https://user-images.githubusercontent.com/8332946/117483134-9cabe200-af65-11eb-97c7-a7db815564a5.png)

**Comment by everruler12** [comment]
Perfect! I'll let you know after I add a check for that modal dialog, and see if your backups start again.

**Comment by ketilmo** [comment]
Awesome Erik, thanks!

Ketil

**Comment by everruler12** [comment]
@ketilmo Hey Ketil, sorry for the long delay. I added a check for the modal, and if it exists, attempt to close it before continuing with the backup.

**Comment by ketilmo** [comment]
Thanks @everruler12, it's appreciated. I have renewed my subscription now but will confirm that the fix works next time it lapses.
