### ISSUE TITLE
R2G ERROR - EDN formatting error: mismatch with original

### ISSUE THREAD

**Issue by necopinus** [everruler12/roam2github#17]
I have been seeing roam2git fail for two consecutive nights with the error:

```
R2G ERROR - EDN formatting error: mismatch with original
```

I’m reporting this per the instructions in [Common error causes](https://github.com/everruler12/roam2github/blob/main/documentation/Common%20error%20causes.md).

The backup in question is for a group, the Yak Collective, that believes in working in public. As such, both our Roam graph (<https://roamresearch.com/#/app/ArtOfGig>) and the backup (<https://github.com/The-Yak-Collective/backups>) are publicly accessible (note that the repo backs up two graphs; the failure is occurring on the ArtOfGig graph).

Happy to try provide additional information or help test things, though I’m hoping that the public nature of both the graph and the backup will make it easier to diagnose this issue.

**Comment by everruler12** [comment]
It appears that this block was corrupted: https://roamresearch.com/#/app/ArtOfGig/page/-MQj-gHbO

![2021 08 08 125201](https://user-images.githubusercontent.com/64292121/128642693-7310fed6-4d59-4ea3-b4e3-be2c1fca0181.gif)

After making these changes, my tests showed that it worked.

Please check again on the next run and confirm.

**Comment by necopinus** [comment]
I wonder what caused that corruption? I don’t think that page should have had many, or any, visitors lately.

Anyways, looks like the backup succeeded this morning, so that must have been it. Thanks!
