### ISSUE TITLE
Started seeing consistent backup failures yesterday

### ISSUE THREAD

**Issue by cori** [everruler12/roam2github#7]
It looks to me like the npm install is failing on Chromium, but I haven't spent any time digging into it.

Started 16 hours ago, or around when 016ce8c was merged.

I'm seeing these logs in the Run Backup step

```
Run cd ..
  cd ..
  git clone -q https://github.com/everruler12/roam2github-test.git roam2github
  cd $_
  npm i
  npm run start -s
  shell: /usr/bin/bash -e {0}
  env:
    R2G_EMAIL: ***
    R2G_PASSWORD: ***
    R2G_GRAPH: ***

> puppeteer@5.5.0 install /home/runner/work/roam-backups/roam2github/node_modules/puppeteer
> node install.js


Chromium (818858) downloaded to /home/runner/work/roam-backups/roam2github/node_modules/puppeteer/.local-chromium/linux-818858
added 66 packages from 83 contributors and audited 66 packages in 10.564s
found 0 vulnerabilities

Error: Process completed with exit code 1.
```

Pretty sure my secrets are correct - the secrets page looks like this

![image](https://user-images.githubusercontent.com/46317/108358102-eaf5e400-71b3-11eb-90d2-2e7e484a8108.png)

And none of those values have changed in Roam in the last day.

**Comment by everruler12** [comment]
Hello Cori,

I did an update yesterday that accidentally replaced the main script, and
would have messed things up for everybody, but I reverted it back a couple
minutes later after realizing my error (and saved it to a new script). The
backups have continued working for me, and I haven't heard from anyone
else, so it's odd that it's failing consistently for you.

I suggest you go ahead and update to the new script by following these
instructions:
https://www.notion.so/Roam2Github-Update-Instructions-c594a2931b694010814001c8a20fa960

Sorry for the inconvenience. If you need any further assistance with this,
please let me know.
(If you're short on time, I'll even get on a Zoom call with you, and
quickly set this up for you remotely at no cost.)

Erik

**Comment by cori** [comment]
Hey Erik thanks - i sort of figured it was something along those lines. I'll follow the update guide later this evening and will update here with the results.

Thanks for the help and the project!

**Comment by everruler12** [comment]
@cori How's it working?

**Comment by takaokay** [comment]
Hi, Erik, thanks to your script roam is now backed up successfully, and I am relieved from losing data.
Github says yesterday disk usage is coming near to the upper limit. 
I am wondering if it is possible to change and reduce the back-up timing of a day or delete old backup automatically. 
Should I periodically delete old files by manual?

**Comment by everruler12** [comment]
I'm closing the issue. Please re-open if you're still experiencing problems.
