### ISSUE TITLE
Disk usage is near full.

### ISSUE THREAD

**Issue by takaokay** [everruler12/roam2github#8]
Hi, Erik, thanks to your script roam is now backed up successfully, and I am relieved from losing data.
Github says yesterday disk usage is coming near to the upper limit.
I am wondering if it is possible to change and reduce the back-up timing of a day or delete old backup automatically.
Should I periodically delete old files by manual?

**Comment by everruler12** [comment]
I think you're referring to the limit of 2000 minutes per month on a free plan for private Action runtime. I also ran into this issue, and in the past week, came up with a solution for free, unlimited usage. You can update with the guide here: https://www.notion.so/Roam2Github-Update-Instructions-c594a2931b694010814001c8a20fa960

**Comment by takaokay** [comment]
I am sorry for this late reply. Thank you for your quick and kind reply. Yes, my problem was the same as you encountered. I just adopted your solution. Thank you.
