### ISSUE TITLE
  Error: fatal: couldn't find remote ref refs/heads/main

### ISSUE THREAD

**Issue by grp06** [everruler12/roam2github#9]
I followed the setup instructions but when I run my workflow I get this: "  Error: fatal: couldn't find remote ref refs/heads/main" attached is a zip of my logs
[logs_5.zip](https://github.com/everruler12/roam2github/files/6040914/logs_5.zip)

**Comment by everruler12** [comment]
This error seems to occur if the `BACKUP_REPO` Secret is formatted incorrectly. If the name of your backup repo were `roam-backup`, the exact value of your Secret should be:
`grp06/roam-backup`

**Comment by everruler12** [comment]
Closing this issue, as a correctly formatted Secret solved the problem for a couple of other people.
